variables:
  CONTAINER_REGISTRY: "registry.star.lab"
  CONTAINER_NAME: "yocto"
  BUILD_VAR_FILE: "build_vars"

before_script:
  - docker info

stages:
  - set_env
  - build
  - publish
  - cleanup

master_env:
  stage: set_env
  script:
    - "echo export COMPLETE_NAME=\"$CONTAINER_REGISTRY/$CONTAINER_NAME:latest\" >> $BUILD_VAR_FILE"
  only: 
    - master
  artifacts:
    paths:
      - $BUILD_VAR_FILE
tag_env:
  stage: set_env
  script:
    - "echo export COMPLETE_NAME=\"$CONTAINER_REGISTRY/$CONTAINER_NAME:$CI_BUILD_TAG\" >> $BUILD_VAR_FILE"
  only: 
    - tags

other_env:
  stage: set_env
  script:
    - "echo export COMPLETE_NAME=\"$CONTAINER_REGISTRY/$CONTAINER_NAME:$CI_PROJECT_ID\" >> $BUILD_VAR_FILE"
  except:
    - master 
    - tags
  artifacts:
    paths:
      - $BUILD_VAR_FILE

build:
  stage: build
  script:
    - source $BUILD_VAR_FILE
    - docker build --rm=true -t $COMPLETE_NAME .

publish:
  stage: publish
  script:
    - source $BUILD_VAR_FILE
    - docker push $COMPLETE_NAME
  only:
    - master
    - tags

cleanup:
  stage: cleanup
  script:
    - source $BUILD_VAR_FILE
    - docker rmi $COMPLETE_NAME

